/*----------------------------------------------------------------------------
  ChucK Strongly-timed Audio Programming Language
    Compiler and Virtual Machine

  Copyright (c) 2003 Ge Wang and Perry R. Cook. All rights reserved.
    http://chuck.stanford.edu/
    http://chuck.cs.princeton.edu/

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
  U.S.A.
-----------------------------------------------------------------------------*/

//-----------------------------------------------------------------------------
// file: chugin.h
// desc: unified header for creating chugins, including the following
//
//   * chuck c++ typedefs and #defines such as t_CKINT, t_CKFLOAT, etc.
//   * macros for chugin components, e.g., member/static variables & functions,
//     contructors, destructors, and operator overloads
//   * chugin DL query API for adding new types to the ChucK type system
//   * chugin DL runtime API for accessing host functionalities across
//     shared-library boundaries
//   * header version string CHUCK_VERSION_STRING
//     (associated with a particular chuck language version)
//   * host/chugin compatibility version
//     (used when a chugin loads to determine chugin:host compatibility)
//
// NOTE: please see the chugins page and the chugins repository for examples
//       https://chuck.stanford.edu/extend/
//       https://github.com/ccrma/chugins/
//
// ALSO: check out the 'chuginate' utility (for generating chugin starter code)
//       available in the chugins repository.
//
// FYI: this file was generated by chuck-o-matic/scripts/chugin-gen-header.sh
//      & combines four minimally needed chuck headers for compiling chugins:
//
//   * chuck_def.h
//   * chuck_symbol.h
//   * chuck_absyn.h
//   * chuck_dl.h
//-----------------------------------------------------------------------------


// all chugins must define __CHUCK_CHUGIN__
#ifndef __CHUCK_CHUGIN__
#define __CHUCK_CHUGIN__
#endif // #ifndef __CHUCK_CHUGIN__

// use CHUGIN_API_VERSION_MAJOR for chugin API major version (as an integer)
#define CHUGIN_API_VERSION_MAJOR CK_DLL_VERSION_MAJOR
// use CHUGIN_API_VERSION_MINOR for chugin API minor version (as an integer)
#define CHUGIN_API_VERSION_MINOR CK_DLL_VERSION_MINOR


